### ISSUE TITLE
ldattach: cannot set line discipline: Invalid argument

### ISSUE THREAD

**Issue by marcioakyama** [norly/elmcan#3] opened 2020-11-04 00:49 UTC
Hi I'm trying to use this module at Ubuntu 20.04, but when I run ldattach comand, it ends with error

when I input 
sudo ./attach-me.sh /dev/ttyUSB0

it shows me that

ldattach: iflag (set/clear): 64/4352
ldattach: opened /dev/ttyUSB0
ldattach: set to raw 38400 8n1: cflag=0xcbf
ldattach: cannot set line discipline: Invalid argument

Do you have any idea why it's not working?

**Comment by norly** [comment] 2020-11-04 00:54
My first guess is that the elmcan module is not loaded.
After compiling, and before running ldattach, you need to run:
`sudo insmod ./elmcan.ko`

**Comment by marcioakyama** [comment] 2020-11-04 01:00
Now I tried to run, but it returns this error

> insmod: ERROR: could not insert module ./elmcan.ko: Operation not permitted

**Comment by norly** [comment] 2020-11-04 01:02
What does `sudo dmesg` say with regard to your inserting the module?

**Comment by marcioakyama** [comment] 2020-11-04 01:40
it shows

Lockdown: insmod: unsigned module loading is restricted; see man kernel_lockdown.7

I saw that it's because of a security restriction. I tried to disable this but I am not successful yet

**Comment by norly** [comment] 2020-11-04 01:50
Okay, so that's not an issue with elmcan then, but rather a matter of how Ubuntu is configured for security.
Let's close this issue then, as your original issue is simply caused by the module not having been loaded before running ldattach :)

Also, keep in mind that can-dev needs to be loaded before elmcan can be inserted. Otherwise you'll get an error in dmesg and insmod will fail. So the final order of commands is something like:
> make
> sudo modprobe can-dev
> sudo insmod ./elmcan.ko
> sudo ./attach-me.sh /dev/ttyUSB0

**Closed by norly** 2020-11-04 01:50 UTC

**Comment by marcioakyama** [comment] 2020-11-04 11:40
Hi! I disabled the kernel lockdon using mokutils, and it worked fine! 
Thanks!

**Comment by norly** [comment] 2020-11-05 14:35
I'm glad to hear. Enjoy!

Also, since this driver seems to be picking up in popularity, I'm curious to know what everyone is using this driver for. I'd appreciate your story :)

**Comment by regenduft** [comment] 2024-05-05 06:37
for me on kernel version 6.5 in ubuntu, the line-discipline 29 didn't work. I then tried different numbers and with ldisc 30 it worked, the kernel module can327 as autoloaded and the can network interface was created, so I knew that 30 was the right ldisc.

**Comment by norly** [comment] 2024-05-05 06:48
ldisc 29 is for the downstream driver in this repository.

For using the upstream driver that is included in Linux v6.0 and up, please refer to the upstream documentation, which does mention ldisc 30. As an example, here is the documentation from Linux v6.1:

https://www.kernel.org/doc/html/v6.1/networking/device_drivers/can/can327.html

**Comment by norly** [comment] 2024-05-05 06:55
I've added a hint to the upstream documentation at the top of the README, so future users don't have to struggle like you did. Thanks for the idea!
